### ISSUE TITLE
"jsonnet: command not found" errors with v6/v8 (v7 works)

### ISSUE THREAD

**Issue by mariozaizar** [zendesk/setup-jsonnet#15]
"jsonnet: command not found" errors with v8 (downgrading to v7 fixed the issue)

* Failure example: https://github.com/zendesk/support-inbound-email/runs/4730245401?check_suite_focus=true
* Fix example: Code: https://github.com/zendesk/support-inbound-email/pull/298/commits/02dd39e1ac708fc8fca772df6b491b0fdd8d7334

This workflow logs:
```
Run zendesk/setup-jsonnet@v8
  with:
    version: latest
  env:
    REPO_NAME: support-inbound-email
    DEFAULT_BRANCH: main
/home/runner/runner/agent/_work/_actions/zendesk/setup-jsonnet/v8/install-jsonnet.sh latest
+ version=latest
+ go install github.com/google/go-jsonnet/cmd/jsonnet@latest
can't load package: package github.com/google/go-jsonnet/cmd/jsonnet@latest: cannot use path@version syntax in GOPATH mode
(node:4719) UnhandledPromiseRejectionWarning: Error: The process '/home/runner/runner/agent/_work/_actions/zendesk/setup-jsonnet/v8/install-jsonnet.sh' failed with exit code 1
    at ExecState._setResult (/home/runner/runner/agent/_work/_actions/zendesk/setup-jsonnet/v8/node_modules/@actions/exec/lib/toolrunner.js:574:25)
    at ExecState.CheckComplete (/home/runner/runner/agent/_work/_actions/zendesk/setup-jsonnet/v8/node_modules/@actions/exec/lib/toolrunner.js:557:18)
    at ChildProcess.<anonymous> (/home/runner/runner/agent/_work/_actions/zendesk/setup-jsonnet/v8/node_modules/@actions/exec/lib/toolrunner.js:451:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:4719) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4719) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Error:
```
cd kubernetes && mkdir -p manifests && jsonnet templates/manifests.jsonnet --jpath ../vendir --string --multi manifests/ && cd ../;

/home/runner/runner/agent/_work/_temp/b6c634ba-35f5-4a1f-922c-8f89f92c53e4.sh: line 20: jsonnet: command not found
```

Found this related thread: https://zendesk.slack.com/archives/C020BGL150B/p1641235945478100?thread_ts=1641232830.473300&amp;cid=C020BGL150B

**Comment by jayzz55** [comment]
Our team finds that upgrading to version 10 - https://github.com/zendesk/setup-jsonnet/releases/tag/v10 have solved this issue.
